# **Data Science Bootcamp, Spring 2025**
---
**Take-Home Assignment #2** \
Cherron Griffith \
Due Date: March 12, 2025

---
---

## **Part 1 - Numpy**
---

In [1]:
# Dataset for the first 4 questions
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

---
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [ ]:
# create 1D arrays containing 5 random integers 
A = np.random.randint(10, size=(5,))
print("A:", A)
B = np.random.randint(10, size=(5,))
print("B:", B)

# vertically stack the arrays 
print("Vertical Stack:")
C = np.vstack((A,B))
print(C)

# horizontally stack the arrays
D = np.hstack((A,B))
print("Horizontal Stack:", D)

A: [1 5 5 7 6]
B: [2 5 4 2 5]
Vertical Stack:
[[1 5 5 7 6]
 [2 5 4 2 5]]
Horizontal Stack: [1 5 5 7 6 2 5 4 2 5]


--- 
2. Find common elements between A and B. [Hint: Intersection of two sets]

In [ ]:
# create 1D arrays containing 5 random integers
A = np.random.randint(10, size=(5,))
print("A:", A)
B = np.random.randint(10, size=(5,))
print("B:", B)

# print the numbers that are in both A and B
print("Common Elements:")
for a in A:
    for b in B:
        if a == b:
            print(a)

A: [3 8 7 8 2]
B: [7 6 2 5 6]
Common Elements:
7
2


---
3. Extract all numbers from A which are within a specific range, ex: between 5 and 10. [Hint: `np.where()` might be useful or boolean masks]

In [ ]:
# create 1D array containing 8 random integers 
A = np.random.randint(10, size=(8,))
print("A:", A)

# print numbers between 5 and 10
mask = (A>5) & (A<10)
filtered_A = A[mask]
print("Numbers between 5 and 10:", filtered_A)


A: [6 0 4 7 1 3 0 7]
Numbers between 5 and 10: [6 7 7]


--- 
4. Filter the rows of `iris_2d` that has petallength (3rd column) > 1.5 and sepallength (1rst column)<5.0

In [55]:
# create filter to only show 
condition = (iris_2d[:, 0] < 5.0) & (iris_2d[:, 2] > 1.5)

# apply filter to iris_2d
filtered = iris_2d[condition]
print(filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


---
## **Part 2: Pandas**
---
1. From df filter the 'Manufacturer', 'Model', and 'Type' for every 20th row starting from 1rst (row 0). \
`df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')`

In [53]:
# read data
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# filter to show only the three columns "Manufacturer", "Model", and "Type"
column_filter = df[['Manufacturer', 'Model', 'Type']]

# filter to show every 20 rows (starting from row1/index0)
df_filter = column_filter.loc[::20,:]
df_filter 


Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

---
2. Replace missing values in Min.Price and Max.Price columns with their respective mean \
`df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')`


In [ ]:
# read data 
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# calculate the mean of "Min.Price" and round to two decimal places
min_mean = df["Min.Price"].mean()
min_mean = np.round(min_mean,2)

# calculate the mean of "Max.Price" and round to two decimal places
max_mean = df["Max.Price"].mean()
max_mean = np.round(max_mean,2)

# alter df to show the means in place of "NaN" in "Min.Price" and "Max.Price"
df["Min.Price"] = df["Min.Price"].fillna(min_mean)
df["Max.Price"] = df["Max.Price"].fillna(max_mean)
df


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small      12.90   15.9      18.80      25.0   
1           NaN   Legend  Midsize      29.20   33.9      38.70      18.0   
2          Audi       90  Compact      25.90   29.1      32.30      20.0   
3          Audi      100  Midsize      17.12   37.7      44.60      19.0   
4           BMW     535i  Midsize      17.12   30.0      21.46      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van      16.60   19.7      22.70      17.0   
89   Volkswagen   Passat  Compact      17.60   20.0      22.40      21.0   
90   Volkswagen  Corrado   Sporty      22.90   23.3      23.70      18.0   
91        Volvo      240  Compact      21.80   22.7      23.50      21.0   
92          NaN      850  Midsize      24.80   26.7      28.50      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

---
3. How to get the rows of a dataframe with row sum > 100? \
`df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))`

In [ ]:
# read data 
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# create filter to only show rows with a sum > 100
condition = np.sum(df,axis=1) > 100

# filter df 
df[condition]

0   1   2   3
0   37  21  33  16
3   39  24  27  24
4   34  36  29  16
5   23  14  38  29
8   31  34  13  26
11  31  26  27  38
14  13  24  29  38